

__Задание 1. Генератор случайных матриц.__

In [2]:
import numpy as np

def matrix_generate(rows, columns, type_="full", eps=0):
    """
    matrix_generate(rows, columns, type_="full", eps=0)

    Создаёт случайную матрицу выбранного типа.

    Если матрицу нужных размеров создать нельзя, выдает
    строку f"Error with type {type_} and shape ({rows},{columns})".

    Parameters
    ----------
    rows : int
        Количество строк в создаваемой матрице.
    columns : int
        Количество столбцов в создаваемой матрице.
    type_ : str, optional
        Тип создаваемой матрицы: "full", "diagonal", "upper_triangular", "lower_triangular", "symmetric",
        "singular" и т.д.
    eps: float, optional
        Дополнительное число, использующееся при генерации для некоторых типов матриц.

    Returns
    -------
    out : ndarray or str
        Возвращает матрицу нужного типа либо сообщение об ошибке.

    Notes
    -----
    Поддерживаемые типы матриц:
        "full", "diagonal", "upper_triangular", "lower_triangular",
        "symmetric", "singular", "step", "perturbation", ...
    """

    if type_ == "full":
        return np.random.random(size=(rows, columns))

    elif type_ == "diagonal":
        if rows != columns:
            return f"Error with type {type_} and shape ({rows},{columns})"
        else:
            return np.diag(np.random.rand(rows))

    elif type_ == "upper_triangular":
        return np.triu(np.random.random(size=(rows, columns)))

    elif type_ == "lower_triangular":
        return np.tril(np.random.random(size=(rows, columns)))

    elif type_ == "symmetric":
        if rows != columns:
            return f"Error with type {type_} and shape ({rows},{columns})"
        else:
            A = np.random.random(size=(rows, columns))
            return (A + A.T) / 2

    elif type_ == "singular":
        if columns < 2:
            return f"Error with type {type_} and shape ({rows},{columns})"
        else:
            A = np.random.random(size=(rows, columns))
            A[:, -1] = A[:, 0]
            return A

    elif type_ == "step":
        if columns > rows:
            return f"Error with type {type_} and shape ({rows},{columns})"
        A = np.triu(np.random.random((rows, rows)), 1) + np.eye(rows)
        indices = list(range(rows))
        np.random.shuffle(indices)
        A = A[indices[:columns], :]
        return A

    elif type_ == "perturbation":
        return np.random.uniform(-eps, eps, size=(rows, columns))

    else:
        return f"Error: Unknown matrix type '{type_}'"


In [14]:
matrix_generate(1, 3)

array([[0.57434916, 0.93467634, 0.79490181]])

In [15]:
matrix_generate(2, 2, type_ = "upper_triangular")

array([[0.5939277 , 0.16261597],
       [0.        , 0.80389439]])

In [16]:
matrix_generate(5, 3, type_ = "upper_triangular")

array([[0.73985933, 0.45117595, 0.60465216],
       [0.        , 0.74488641, 0.10399908],
       [0.        , 0.        , 0.67153523],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

In [17]:
matrix_generate(4, 4, type_ = "symmetric")

array([[0.89613194, 0.46916328, 0.45973162, 0.44287298],
       [0.46916328, 0.61406597, 0.33847741, 0.47390672],
       [0.45973162, 0.33847741, 0.29893163, 0.33401612],
       [0.44287298, 0.47390672, 0.33401612, 0.88173356]])

In [18]:
matrix_generate(4, 3, type_ = "step")

array([[0.        , 1.        , 0.35620364, 0.45788038],
       [0.        , 0.        , 1.        , 0.70898796],
       [0.        , 0.        , 0.        , 1.        ]])

In [19]:
matrix_generate(4, 1, type_ = "symmetric")

'Error with type symmetric and shape (4,1)'

__Задание 2. Вычисление матричных норм и числа обусловленности.__

In [9]:
from scipy.linalg import eigvals
import numpy as np

def l1_norm(x):
    return np.sum(np.abs(x))

def l2_norm(x):
    return np.sqrt(np.sum(x**2))

def max_norm(x):
    return np.max(np.abs(x))

def l1_norm_matrix(A):
    return np.max(np.sum(np.abs(A), axis=0))

def l2_norm_matrix(A):
    eigenvalues = eigvals(A @ A.T)
    return np.sqrt(np.max(eigenvalues))

def max_norm_matrix(A):
    return np.max(np.sum(np.abs(A), axis=1))

def cond_num(A, norm="L1"):
    A_inv = np.linalg.inv(A)
    if norm == "L1":
        return l1_norm_matrix(A) * l1_norm_matrix(A_inv)
    elif norm == "L2":
        return l2_norm_matrix(A) * l2_norm_matrix(A_inv)
    elif norm == "inf":
        return max_norm_matrix(A) * max_norm_matrix(A_inv)
